version: '3'

services:
  registry:
    image: mareksuchanek/docker-registry
    restart: always
    environment:
      GC_CRON: "*/5 * * * *"
    volumes:
      - ./data:/var/lib/registry
      - ./registry.yml:/etc/docker/registry/config.yml:ro
      - ./htpasswd:/htpasswd:ro
  
  registry-ui:
    image: joxit/docker-registry-ui:2.2.0-debian
    restart: always
    ports:
      - 127.0.0.1:8080:80
    environment:
      REGISTRY_TITLE: "My example registry"
      SINGLE_REGISTRY: true
      DELETE_IMAGES: true
      NGINX_PROXY_PASS_URL: http://registry:5000
