version: '3'

services:
  registry:
    #image: registry:2.8.1
    image: registry:local
    restart: always
    volumes:
      - ./data:/var/lib/registry
      - ./registry.yml:/etc/docker/registry/config.yml:ro
      - ./htpasswd:/htpasswd:ro
      - ./cron/cron-test:/etc/periodic/15min/test
  
  registry-ui:
    image: joxit/docker-registry-ui:2.2.0-debian
    restart: always
    ports:
      - 127.0.0.1:8080:80
    environment:
      REGISTRY_TITLE: "My example registry"
      SINGLE_REGISTRY: true
    #  REGISTRY_URL: http://localhost:5000
      DELETE_IMAGES: true
      NGINX_PROXY_PASS_URL: http://registry:5000

  # proxy:
  #   image: nginx:1.21.6
  #   restart: always
  #   ports:
  #     - 127.0.0.1:8080:8080
  #   #  - 127.0.0.1:5000:5000
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
  #     - ./nginx/logs:/var/logs
